---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Go
        uses: actions/setup-go@v5.2.0
        with:
          go-version: 1.23
      - name: Set GOFLAGS
        run: echo "GOFLAGS=-buildvcs=false" >> $GITHUB_ENV
      - name: Check go format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - name: Vet go code
        run: go vet ./...
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2024.1.1"
          install-go: false
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -ldflags "-s -w" -o conway
